services:
  mergin-maps-redis:
    image: redis:alpine
    x-runtipi:
      add_to_main_network: true

  mergin-maps:
    image: lutraconsulting/merginmaps-backend:2025.7.3
    depends_on:
      - mergin-maps-redis
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      CELERY_BROKER_URL: "redis://mergin-maps-redis:6379/0"
      MERGIN_BASE_URL: ${MERGIN_BASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      SECURITY_BEARER_SALT: ${SECURITY_BEARER_SALT}
      SECURITY_EMAIL_SALT: ${SECURITY_EMAIL_SALT}
      SECURITY_PASSWORD_SALT: ${SECURITY_PASSWORD_SALT}
    volumes:
      - ${APP_DATA_DIR}/data:/data
    x-runtipi:
      is_main: true
      internal_port: 5000
      add_to_main_network: true

  mergin-maps-worker:
    image: lutraconsulting/merginmaps-backend:2025.7.3
    command: ["celery", "-A", "application.celery", "worker", "--loglevel=info"]
    depends_on:
      - mergin-maps-redis
      - mergin-maps
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      CELERY_BROKER_URL: "redis://mergin-maps-redis:6379/0"
      MERGIN_BASE_URL: ${MERGIN_BASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      SECURITY_BEARER_SALT: ${SECURITY_BEARER_SALT}
      SECURITY_EMAIL_SALT: ${SECURITY_EMAIL_SALT}
      SECURITY_PASSWORD_SALT: ${SECURITY_PASSWORD_SALT}
    volumes:
      - ${APP_DATA_DIR}/data:/data
    x-runtipi:
      add_to_main_network: true

  mergin-maps-beat:
    image: lutraconsulting/merginmaps-backend:2025.7.3
    command: ["celery", "-A", "application.celery", "beat", "--loglevel=info"]
    depends_on:
      - mergin-maps-redis
      - mergin-maps
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      CELERY_BROKER_URL: "redis://mergin-maps-redis:6379/0"
      MERGIN_BASE_URL: ${MERGIN_BASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      SECURITY_BEARER_SALT: ${SECURITY_BEARER_SALT}
      SECURITY_EMAIL_SALT: ${SECURITY_EMAIL_SALT}
      SECURITY_PASSWORD_SALT: ${SECURITY_PASSWORD_SALT}
    volumes:
      - ${APP_DATA_DIR}/data:/data
    x-runtipi:
      add_to_main_network: true
x-runtipi:
  schema_version: 2
  overrides: []
