services:
  nginx:
    image: geonode/nginx:latest
    environment:
      RESOLVER: 127.0.0.11
    depends_on:
      - django
      - geoserver
    volumes:
      - ${APP_DATA_DIR}/statics:/mnt/volumes/statics
    x-runtipi:
      is_main: true
      internal_port: 80
      add_to_main_network: true

  db:
    image: geonode/postgis:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      GEONODE_GEODATABASE: geonode_data
    volumes:
      - ${APP_DATA_DIR}/db:/var/lib/postgresql/data
    x-runtipi:
      add_to_main_network: true

  django:
    image: geonode/geonode:5.0.2
    environment:
      GEONODE_INSTANCE_NAME: geonode
      GEONODE_LB_HOST_IP: ${GEONODE_LB_HOST_IP}
      GEONODE_LB_PORT: ""
      SITEURL: http://${GEONODE_LB_HOST_IP}/
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: postgres
      DATABASE_URL: postgis://postgres:postgres@db:5432/geonode
      GEODATABASE_URL: postgis://postgres:postgres@db:5432/geonode_data
      DEFAULT_BACKEND_DATASTORE: datastore
      GEOSERVER_WEB_UI_LOCATION: http://geoserver:8080/geoserver/
      GEOSERVER_PUBLIC_LOCATION: http://${GEONODE_LB_HOST_IP}/geoserver/
      BROKER_URL: redis://redis:6379/1
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_EMAIL: admin@example.com
      C_FORCE_ROOT: "True"
      IS_CELERY: "False"
    command: uwsgi --ini /usr/src/geonode/uwsgi.ini
    volumes:
      - ${APP_DATA_DIR}/statics:/mnt/volumes/statics
      - ${APP_DATA_DIR}/geoserver_data:/geoserver_data/data
    depends_on:
      - db
      - redis
    x-runtipi:
      add_to_main_network: true

  geoserver:
    image: geonode/geoserver:2.27.5-latest
    environment:
      GEONODE_LB_HOST_IP: ${GEONODE_LB_HOST_IP}
      GEONODE_LB_PORT: ""
      SUBSTITUTION_URL: http://${GEONODE_LB_HOST_IP}/
      NGINX_BASE_URL: http://${GEONODE_LB_HOST_IP}/
      DATABASE_HOST: db
      DATABASE_PORT: "5432"
      GEONODE_GEODATABASE: geonode_data
      GEONODE_GEODATABASE_USER: postgres
      GEONODE_GEODATABASE_PASSWORD: postgres
    volumes:
      - ${APP_DATA_DIR}/geoserver_data:/geoserver_data/data
    depends_on:
      - django
      - db
    x-runtipi:
      add_to_main_network: true

  redis:
    image: redis:7-alpine
    x-runtipi:
      add_to_main_network: true

  celery:
    image: geonode/geonode:5.0.2
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: postgres
      DATABASE_URL: postgis://postgres:postgres@db:5432/geonode
      GEODATABASE_URL: postgis://postgres:postgres@db:5432/geonode_data
      DEFAULT_BACKEND_DATASTORE: datastore
      BROKER_URL: redis://redis:6379/1
      C_FORCE_ROOT: "True"
      IS_CELERY: "True"
    command: celery-cmd
    volumes:
      - ${APP_DATA_DIR}/statics:/mnt/volumes/statics
    depends_on:
      - db
      - redis
    x-runtipi:
      add_to_main_network: true

x-runtipi:
  schema_version: 2
  overrides: []
