services:
  anythingllm:
    image: mintplexlabs/anythingllm:master
    environment:
      STORAGE_DIR: /app/server/storage
      OLLAMA_BASE_URL: http://ollama:11434
      DB_provider: postgres
      DB_host: ${DB_HOST}
      DB_port: "5433"
      DB_user: ${DB_USER}
      DB_password: ${DB_PASSWORD}
      DB_database: ${DB_NAME}
    volumes:
      - ${APP_DATA_DIR}/anythingllm:/app/server/storage
    depends_on:
      - ollama
    x-runtipi:
      is_main: true
      internal_port: 3001
      add_to_main_network: true
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ${APP_DATA_DIR}/ollama:/root/.ollama
x-runtipi:
  schema_version: 2
  overrides: []
